import type { Meeting } from "./types";
import {
  addDays,
  dayOfWeek,
  escapeText,
  foldLine,
  formatLocalStamp,
  formatUtcStamp,
  parseBannerTime,
  untilStamp,
} from "./util";

const ICS_DAY = ["SU", "MO", "TU", "WE", "TH", "FR", "SA"] as const;
const PRODID = "-//Kigani Systems//parse.kigani-systems.com//EN";

/**
 * Hardcoded because Banner exposes no timezone on any endpoint we call.
 * Correct for Swarthmore. Adding an institution in another zone means
 * changing this alongside the VTIMEZONE block and newYorkOffsetMinutes().
 */
export const TZID = "America/New_York";

/**
 * A VTIMEZONE is not optional here. The term spans 2026-11-01, so a UTC
 * DTSTART with a weekly RRULE would shift every class after that date by an
 * hour. Shipping the rules inline also means clients with stale tzdata still
 * resolve the same wall-clock times we computed.
 */
const VTIMEZONE = [
  "BEGIN:VTIMEZONE",
  `TZID:${TZID}`,
  "X-LIC-LOCATION:America/New_York",
  "BEGIN:DAYLIGHT",
  "TZOFFSETFROM:-0500",
  "TZOFFSETTO:-0400",
  "TZNAME:EDT",
  "DTSTART:19700308T020000",
  "RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU",
  "END:DAYLIGHT",
  "BEGIN:STANDARD",
  "TZOFFSETFROM:-0400",
  "TZOFFSETTO:-0500",
  "TZNAME:EST",
  "DTSTART:19701101T020000",
  "RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU",
  "END:STANDARD",
  "END:VTIMEZONE",
];

export interface BuildOptions {
  /** Overrides Banner's endDate. Used by the "last class date" control. */
  lastDate?: Date;
  /** Injected in tests so golden-file output is deterministic. */
  now?: Date;
  calendarName?: string;
}

/**
 * First date on or after `start` whose weekday is in `days`.
 *
 * Banner's startDate is the term's first day, not the section's first meeting:
 * a Thursday-only lab still reports startDate = Monday 08/31. Emitting that as
 * DTSTART with BYDAY=TH is undefined behaviour in practice — some clients drop
 * the first occurrence, others synthesise a Monday meeting that does not exist.
 */
export function firstOccurrence(start: Date, days: number[]): Date | null {
  if (days.length === 0) return null;
  for (let i = 0; i < 7; i++) {
    const candidate = addDays(start, i);
    if (days.includes(dayOfWeek(candidate))) return candidate;
  }
  return null;
}

function countOccurrences(first: Date, last: Date, days: number[], cap: number): number {
  let count = 0;
  for (let d = first; d.getTime() <= last.getTime(); d = addDays(d, 1)) {
    if (days.includes(dayOfWeek(d))) {
      count++;
      if (count >= cap) return count;
    }
  }
  return count;
}

/**
 * Stable and content-derived, so re-running the tool and re-importing updates
 * the existing events instead of creating a second copy of every class. This
 * is the difference between a student being able to re-run after a schedule
 * change and them ending up with a duplicated calendar.
 */
function uid(meeting: Meeting): string {
  const dayKey = meeting.days.map((d) => ICS_DAY[d]).join("") || "NONE";
  return `${meeting.term}-${meeting.crn}-${meeting.beginTime}-${dayKey}@parse.kigani-systems.com`;
}

function summaryOf(meeting: Meeting): string {
  return `${meeting.subject} ${meeting.courseNumber} ${meeting.title}`.trim();
}

function descriptionOf(meeting: Meeting, lastDate: Date): string {
  const lines = [`CRN ${meeting.crn}`];
  if (meeting.instructors.length > 0) {
    lines.push(`Instructor: ${meeting.instructors.join(", ")}`);
  }
  if (meeting.meetingTypeDescription) lines.push(meeting.meetingTypeDescription);
  const end = `${lastDate.getUTCMonth() + 1}/${lastDate.getUTCDate()}/${lastDate.getUTCFullYear()}`;
  lines.push(`Repeats until ${end}, per Banner.`);
  lines.push("Generated by parse.kigani-systems.com");
  return lines.join("\n");
}

export function buildEvent(meeting: Meeting, options: BuildOptions = {}): string[] {
  const lastDate = options.lastDate ?? meeting.endDate;
  const first = firstOccurrence(meeting.startDate, meeting.days);
  if (!first || first.getTime() > lastDate.getTime()) return [];

  const begin = parseBannerTime(meeting.beginTime);
  const end = parseBannerTime(meeting.endTime);

  // A meeting whose end time precedes its start time has crossed midnight.
  // Vanishingly rare for classes, but a negative-duration event renders as a
  // corrupt entry rather than failing loudly, so handle it explicitly.
  const endDay = end.hour * 60 + end.minute <= begin.hour * 60 + begin.minute ? addDays(first, 1) : first;

  const dtstamp = formatUtcStamp((options.now ?? new Date()).getTime());

  const lines = [
    "BEGIN:VEVENT",
    `UID:${uid(meeting)}`,
    `DTSTAMP:${dtstamp}`,
    `DTSTART;TZID=${TZID}:${formatLocalStamp(first, begin.hour, begin.minute)}`,
    `DTEND;TZID=${TZID}:${formatLocalStamp(endDay, end.hour, end.minute)}`,
  ];

  if (countOccurrences(first, lastDate, meeting.days, 2) > 1) {
    const byday = meeting.days
      .slice()
      .sort((a, b) => a - b)
      .map((d) => ICS_DAY[d])
      .join(",");
    lines.push(`RRULE:FREQ=WEEKLY;BYDAY=${byday};UNTIL=${untilStamp(lastDate)}`);
  }

  lines.push(`SUMMARY:${escapeText(summaryOf(meeting))}`);
  if (meeting.location) lines.push(`LOCATION:${escapeText(meeting.location)}`);
  lines.push(`DESCRIPTION:${escapeText(descriptionOf(meeting, lastDate))}`);
  lines.push("TRANSP:OPAQUE");
  lines.push("END:VEVENT");
  return lines;
}

export function buildCalendar(meetings: Meeting[], options: BuildOptions = {}): string {
  const lines = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    `PRODID:${PRODID}`,
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    `X-WR-CALNAME:${escapeText(options.calendarName ?? "Class Schedule")}`,
    `X-WR-TIMEZONE:${TZID}`,
    ...VTIMEZONE,
  ];

  for (const meeting of meetings) lines.push(...buildEvent(meeting, options));
  lines.push("END:VCALENDAR");

  // RFC 5545 mandates CRLF, and a trailing CRLF. Outlook in particular is
  // unforgiving about bare LF.
  return lines.map(foldLine).join("\r\n") + "\r\n";
}
